spring:
  session:
    store-type: jdbc
  profiles:
    include: oauth
  datasource:
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true
  jpa:
    show_sql: true
 #   properties:
 #     hibernate:
 #       dialect: org.hibernate.dialect.MySQL5InnoDBDialect